### ISSUE TITLE
Cyberjack

### ISSUE THREAD

**Issue by TheUltimateKaren** [HeyOmae/OMA3#1385]
The essence costs on the higher rank cyberjacks is wrong for essence calculations

**Comment by dethstrobe** [comment]
Are you sure 
src: SR6 p284
<img width="830" alt="image" src="https://github.com/HeyOmae/OMA3/assets/6279187/08870a79-7b16-4353-b6f3-6574715f3069">

Seems to align with the codes in prod
<img width="561" alt="image" src="https://github.com/HeyOmae/OMA3/assets/6279187/0f23fe32-4a05-40f9-b213-03932396ad22">

**Comment by dethstrobe** [comment]
Oh I see, when you buy one, it's reducing essence by a lot for some reason. Looking into it.

**Comment by dethstrobe** [comment]
The data has a rating attribute, which for other cyberware is used as a multiplier for cost and/or essence. Anyway, I'll be removing that. Should be fixed shortly.

**Comment by dethstrobe** [comment]
I'm a liar, this will take longer than I thought. I'm going to try and fix this so that the rating actually updates the essence correctly and doesn't if it's not supposed to effect essence. It looks like I just hacked it together to get it close enough for most cyberware, but obviously not perfect. Cyberjacks' essence is just the symptom. Anyway, I'm hoping it should be pretty doable to get done in a few days.

**Comment by dethstrobe** [comment]
Should be fixed now.
