### ISSUE TITLE
Issue while creating a runner

### ISSUE THREAD

**Issue by khAja13** [HeyOmae/OMA3#1583]
Though I clicked on "Create runner" and even if I just come back without creating it, I can still see a runner is being created without any name.

**Comment by dethstrobe** [comment]
Each runner needs a unique name which can be found on the info page.

You can also leave their name blank which still counts as a unique name...oddly enough. If you don't give them a name, because no text is impossible to select, their display name on the home page get's defaulted to their indexedDB id, which is a database that is on your local browser.

So I think all you need to do is give your runner a unique name. Then you can create a new runner.

**Comment by dethstrobe** [comment]
I'm going to close this for now. Let me know if there is still a problem.
